name: Run maven for every push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Maven
      run: mvn -B clean install
