name: Run maven for every push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Import Secrets
      uses: RichiCoder1/vault-action@v0.10.2
      with:
        url: https://stage.vault.int.camunda.com
        method: github
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        secrets: |
          secrets/common/jenkins/main NEXUS_APP_CAMUNDA_COM_PSW | NEXUS_APP_CAMUNDA_COM_PSW;
          secrets/common/jenkins/main NEXUS_APP_CAMUNDA_COM_USR | NEXUS_APP_CAMUNDA_COM_USR;
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Maven
      run: mvn -B clean install
